### ISSUE TITLE
will it support image to image generation in the future?

### ISSUE THREAD

**Issue by keno-log** [RayKitajima/ComfyBridge#1]
Nice work,thanks!will it support i2i t2v i2v in future?

**Comment by RayKitajima** [comment]
It would be useful if there were.
I don't use i2i or i2v at the moment, but I'll give it a go one of these days.

(It might be quicker if you write down what configuration you're using 😎)

**Comment by RayKitajima** [comment]
hi, @keno-log 

Try the i2i demo added ✨
https://github.com/RayKitajima/ComfyBridge/tree/main/demo/i2i

I think i2v might also be able to do it, but I haven't tried it.

**Comment by RayKitajima** [comment]
Hi, @keno-log,

The i2i demo seems to be of a certain usefulness, so I'll close this issue.

If you have any requests or ideas, please feel free to create an issue.
Thanks!
