### ISSUE TITLE
Use case and i2i support

### ISSUE THREAD

**Issue by walnutbread24** [RayKitajima/ComfyBridge#2]
Hi RayKitajima,

Great work. I am also curious to know if you are working on i2i support. 

Also, what is your use case of this project? This project is helpful to me because I am building a public facing comfyui API endpoint. I assume your use case is similar. If so, once the endpoint is deployed, the handling of files, both input and output, could be a bit complex and will involve interfacing cloud storage like s3. Curious to know if you have similar use case and your thoughts. 

Thanks.

**Comment by RayKitajima** [comment]
Hi, @nouveauciel 

I didn't know much about i2i, so I did a bit of research and found that the current ComfyBridge implementation supports it.

I've added a demo so you can try it out.
https://github.com/RayKitajima/ComfyBridge/tree/main/demo/i2i

I'm working on supporting various generative services in my [Generative Radio app](https://github.com/RayKitajima/RadioStarlight) for macOS, which currently only supports the OpenAI API. The app uses image generation to create cover images and avatars on the fly.

And also, The OpenAI bridge library I was using is now deprecated, so I developed a generic API bridge for Swift to connect to OpenAI and other services like LM Studio and ComfyUI.

Text-to-text generation usually has a simple interface, but ComfyUI, a popular text-to-image software, has a more complex interface. I need to wrap the ComfyUI API to demonstrate image generation for my radio application users.

The applications are quite different, but I hope this project will go in a direction that will help a lot of people.

**Comment by walnutbread24** [comment]
Hi @RayKitajima,

Thanks for your reply. 

FYI - I came across another implementation that might be of interest to you. It is for a different use case -- not sure if it will be helpful to you. [https://github.com/fofr/cog-comfyui](url) Basically, the author uses comfyui.py as a ComfyUI wrapper and use predict.py as the entrypoint.

**Comment by RayKitajima** [comment]
HI, @nouveauciel,

Thanks for telling me. It's an interesting project.

I wish you well with your project!
